services:
  api:
    image: spotify-app-api:latest
    #platform: linux/amd64
    build: api/.
    ports:
    - "8888:8888"
    command: npm start

  frontend:
    image: spotify-app-client:latest
    #platform: linux/amd64
    build: client/.
    ports:
    - "3000:3000"
    command: npm start